#//<2013/8/14-28207-queenie, MTK patch to remove red screen when crashes
#ifdef PARTIAL_BUILD 
ccflags-y += -DPARTIAL_BUILD
#endif
#//>2013/8/14-28207-queenie
obj-$(CONFIG_MTK_AEE_AED) += aed.o
aed-y := aed-main.o aed-debug.o aed-process.o
